# Matemática para Ciencia de los Datos

- Documento base: Saúl Calderón, Žiga Emeršič, Ángel García, Blaž Meden, Felipe Meza, Martín Solís, Juan Esquivel, Mauro Méndez, Manuel Zumbado,  Luis-Alexánder Calvo-Valverde

# Espacio generado, proyección y espacio nulo

Un **espacio generado** de un conjunto de vectores $\left\{ \vec{a}_{1},\vec{a}_{2},\ldots,\vec{a}_{m}\right\} \qquad\vec{a}_{i}\in\mathbb{R}^{n}$ es el conjunto de vectores que pueden ser expresados como combinación
lineal de tales vectores:

\begin{equation}
\textrm{espacioGenerado}\left(\left\{ \vec{a}_{1},\vec{a}_{2},\ldots,\vec{a}_{m}\right\} \right)=\left\{ \vec{v}:\vec{v}=\sum_{i=1}^{m}x_{i}\vec{a}_{i}\qquad x_{i}\in\mathbb{R}^{1}\right\} .
\end{equation}

Puede demostrarse que si el conjunto de vectores $\left\{ \vec{a}_{1},\vec{a}_{2},\ldots,\vec{a}_{m}\right\} \qquad\vec{a}_{i}\in\mathbb{R}^{n}$ es **linealmente independiente** (con $m\geq n$), el espacio
generado por tal conjunto de vectores es: 

\begin{equation}
\textrm{espacioGenerado}\left(\left\{ \vec{a}_{1},\vec{a}_{2},\ldots,\vec{a}_{m}\right\} \right)=\mathbb{R}^{n}.
\end{equation}

Por ejemplo, los vectores unitarios $\hat{i}=\begin{bmatrix}1\\
0\\
0
\end{bmatrix}$, $\hat{j}=\begin{bmatrix}0\\
1\\
0
\end{bmatrix}$ y $\hat{k}=\begin{bmatrix}0\\
0\\
1
\end{bmatrix}$ son linealmente independientes, por lo que entonces es fácil observar que la combinación lineal de tales vectores puede generar cualquier vector en el espacio $\mathbb{R}^{3}$. Por ejemplo, un vector $\vec{v}=\begin{bmatrix}3\\
5\\
7
\end{bmatrix}$ se puede representar como: 

\begin{equation}
\vec{v}=3\hat{i}+5\hat{j}+7\hat{k}=3\,\begin{bmatrix}1\\
0\\
0
\end{bmatrix}+5\,\begin{bmatrix}0\\
1\\
0
\end{bmatrix}+7\,\begin{bmatrix}0\\
0\\
1
\end{bmatrix}
\end{equation}

por lo que entonces $\vec{v}\in\textrm{espacioGenerado}\left(\left\{ \vec{i},\vec{j},\vec{k}\right\} \right)=\mathbb{R}^{3}$, con en este caso $x_{1}=3$, $x_{2}=5$ y $x_{3}=7$.

**La proyección** **de un vector** $\vec{y}\in\mathbb{R}^{n}$ en el espacio generado por el conjunto de vectores $\left\{ \vec{a}_{1},\vec{a}_{2},\ldots,\vec{a}_{m}\right\} \qquad\vec{a}_{i}\in\mathbb{R}^{n}$ corresponde al vector $\vec{v}\in\textrm{espacioGenerado}\left(\left\{ \vec{a}_{1},\vec{a}_{2},\ldots,\vec{a}_{m}\right\} \right)$ tal que $\vec{v}\in\mathbb{R}^{n}$ esté lo más cerca posible del vector $\vec{y}\in\mathbb{R}^{n}$, medido, por ejemplo, con una norma euclidiana $\left\Vert \vec{v}-\vec{y}\right\Vert _{2}$ y se puede definir formalmente como: 

\begin{equation}
\textrm{proy}\left(\vec{y};\left\{ \vec{a}_{1},\vec{a}_{2},\ldots,\vec{a}_{m}\right\} \right)=\textrm{argmin}_{\vec{v}\in\textrm{espacioGenerado}\left(\left\{ \vec{a}_{1},\vec{a}_{2},\ldots,\vec{a}_{m}\right\} \right)}\left\Vert \vec{v}-\vec{y}\right\Vert _{2}.
\end{equation}

Por otra parte, el **espacio de columnas** de una matriz $A\in\mathbb{R}^{m\times n}$ denotado como $\mathcal{C}\left(A\right)$ corresponde al espacio generado por las columnas de la matriz $A$, lo cual se representa como sigue: 

\begin{equation}
\mathcal{C}\left(A\right) = \left\{ \vec{v}\in\mathbb{R}^{m}:\vec{v}=A\,\vec{x},\;\vec{x}\in\mathbb{R}^{m},\:A\in\mathbb{R}^{n\times m}\right\} ,
\end{equation}

donde recordemos que la multiplicación matricial $A\,\vec{x}$ corresponde a una combinación lineal del vector $\vec{x}$:

\begin{equation}
A\,\overrightarrow{x}=\begin{bmatrix}| & | & \ldots & |\\
\vec{a}_{:,1} & \vec{a}_{:,2} & \ldots & \vec{a}_{:,n}\\
| & | & \ldots & |
\end{bmatrix}\,\begin{bmatrix}x_{1}\\
x_{2}\\
\vdots\\
x_{n}
\end{bmatrix}=x_{1}\left[\vec{a}_{:,1}\right]+x_{2}\left[a_{:,2}\right]+\ldots+x_{n}\left[a_{:,n}\right],
\end{equation}

por lo que entonces el espacio de columnas de la matriz $A$ equivale a:

\begin{equation}
{\mathcal{C}\left(A\right)} = espacioGenerado\left(\left\{ \vec{a}_{:,1},\vec{a}_{:,2},\ldots,\vec{a}_{:,n}\right\} \right)=\left\{ v:v=\sum_{i=1}^{n}x_{i}\vec{a}_{:,i}\qquad x_{i}\in\mathbb{R}^{1}\right\} .
\end{equation}

Asumiendo que $A$ es de **rango completo** y que $n<m$ se tiene que la proyección del vector $\vec{y}\in\mathbb{R}^{n}$ en el espacio de columnas de la matriz $A$ está dado por: 

\begin{equation}
\textrm{proy}\left(\vec{y};A\right)=\textrm{argmin}_{\vec{v}\in\mathcal{C}\left(A\right)}\left\Vert \vec{v}-\vec{y}\right\Vert _{2}=\textrm{argmin}_{\vec{x}}\sqrt{\left(A\:\vec{x}-\vec{y}\right)\cdotp\left(A\:\vec{x}-\vec{y}\right)}
\end{equation}

\begin{equation}
\Rightarrow\textrm{proy}\left(\vec{y};A\right)=\textrm{argmin}_{\vec{x}}\sqrt{\left(A\:\vec{x}-\vec{y}\right)^{T}\left(A\:\vec{x}-\vec{y}\right)}
\end{equation}

El encontrar el vector que minimice la ecuación $\left(A\:\vec{x}-\vec{y}\right)^{T}\left(A\:\vec{x}-\vec{y}\right)$
se le llama el problema de los **mínimos cuadrados**. Nos preocupamos de tal ecuación, pues usualmente se eleva el cuadrado la ecuación original de la proyección, dado que tomar su cuadrado no altera el mínimo:

\begin{equation}
\textrm{argmin}_{\vec{v}\in\mathcal{C}\left(A\right)}\left\Vert \vec{v}-\vec{y}\right\Vert _{2}^{2}=\textrm{argmin}_{\vec{x}}\left(A\:\vec{x}-\vec{y}\right)\cdotp\left(A\:\vec{x}-\vec{y}\right).
\end{equation}

Este tema se retomará más adelante, una vez que se haya definido el concepto de gradiente matricial y se demostrará que: 

\begin{equation}
\textrm{proy}\left(\vec{y};A\right)=\textrm{argmin}_{\vec{v}\in\mathcal{C}\left(A\right)}\left\Vert \vec{v}-\vec{y}\right\Vert _{2}=A\,\left(A^{T}A\right)^{-1}A^{T}\vec{y}
\end{equation}

Para el caso en que $A$ está formada por una sola columna $\vec{a}\in\mathbb{R}^{m}$ (correspondiente a un espacio generador de un vector), se tiene el caso especial de la proyección de un vector sobre otro vector:

\begin{equation}
\textrm{proy}\left(\vec{y};\vec{a}\right)=\frac{\vec{a}\,\vec{a}^{T}}{\vec{a}^{T}\,\vec{a}}\vec{y}
\end{equation}

El **espacio nulo** de una matriz $A\in\mathbb{R}^{m\times n}$, se define como el conjunto de todos los vectores que al multiplicarse con la matriz $A$ resultan en $0$, y se denota como 

\begin{equation}
\mathcal{N}\left(A\right)=\left\{ \vec{x}\in\mathbb{R}^{n}:A\,\vec{x}=0\right\} 
\end{equation}

# **Ejemplos** 


## Ejemplo 1: Mismo número de vectores base $m$ y dimensionalidad del vector  $n$, vectores base linealmente independientes.
Dados los vectores base independientes $$\vec{a}_{1}=\begin{bmatrix}0.5\\
0\\
0
\end{bmatrix}, \vec{a}_{2}=\begin{bmatrix}0\\
0.25\\
0
\end{bmatrix},  \vec{a}_{3}=\begin{bmatrix}0\\
0\\
2
\end{bmatrix}$$
Calcular el vector de proyección  $\textrm{proy}\left(\vec{y};A\right)\in\mathbb{R}^{3}$ con $ \vec{y}=\begin{bmatrix}1\\
2\\
3
\end{bmatrix}$ y evaluar su error.

In [1]:
import numpy as np
from numpy import linalg as LA

def projectInvertible(y, A): 
  """
  y: column vector, 2d array
  A: n x m matrix, 2d array
  """
  At = np.transpose(A)
  invMatrix = LA.inv(np.matmul(At,A))
  return np.matmul( np.matmul(np.matmul(A,invMatrix), At), y)

def calculateProjectionError(v, y):
  """
  Calcualte projection error by using the euclidian distance
  """
  return LA.norm(v - y, 2)
  
y = np.array    ([[1.0], 
                  [2.0], 
                  [3.0]])

A = np.array    ([ [0.5, 0, 0], 
                   [0, 0.25, 0], 
                   [0, 0, 2]])
#calculate the projection
projY_A = projectInvertible(y,A)
print("Vector proyectado: ")
print(projY_A)
#calculate its error, which should be zero for invertible A, or lineally independent base vectors
print("Error de proyección: ")
error = calculateProjectionError(projY_A, y)
print(error)

Vector proyectado: 
[[1.]
 [2.]
 [3.]]
Error de proyección: 
0.0


## Ejemplo 2: Mismo número de vectores base $m$ y dimensionalidad del vector $n$, vectores base linealmente dependientes
$$
\vec{a}_{1}=\begin{bmatrix}0.5\\
0\\
0
\end{bmatrix}, \vec{a}_{2}=\begin{bmatrix}1\\
0\\
0
\end{bmatrix}  \vec{a}_{3}=\begin{bmatrix}0\\
1\\
2
\end{bmatrix}
$$
Calcular el vector de proyección  $\textrm{proy}\left(\vec{y};A\right)\in\mathbb{R}^{3}$ con $ \vec{y}=\begin{bmatrix}1\\
2\\
3
\end{bmatrix}$ y evaluar su error.

In [2]:
from numpy.linalg import pinv

def projectNonInvertible(y, A): 
  """
  y: column vector, 2d 
  A: n x m matrix, 2d 
  """
  At = np.transpose(A)
  invMatrix = LA.pinv(np.matmul(At,A))
  return np.matmul( np.matmul(np.matmul(A,invMatrix), At), y)

A = np.array([[0.5, 1.0, 0.0], [0.0, 0.0, 1.0], [0.0, 0.0, 2.0]])
y = np.array([[1.0], [2.0], [3.0]])
#calculate the projection
projY_A = projectNonInvertible(y,A)

print("Vector proyectado")
print(projY_A)
print("Error de proyección: ")
error = calculateProjectionError(projY_A, y)
print(error)

Vector proyectado
[[1. ]
 [1.6]
 [3.2]]
Error de proyección: 
0.4472135954999579


### Ejemplo 3: Más vectores base $m$ que la dimensionalidad del vector $n$
Con los siguientes vectores base $$\vec{a}_{1}=\begin{bmatrix}0.5\\
0\\
0
\end{bmatrix}, \vec{a}_{2}=\begin{bmatrix}0\\
0.25\\
3
\end{bmatrix}, \vec{a}_{3}=\begin{bmatrix}0\\
0\\
2
\end{bmatrix}, \vec{a}_{4}=\begin{bmatrix}23\\
5\\
3
\end{bmatrix}$$

Calcular el vector de proyección  $\textrm{proy}\left(\vec{y};A\right)\in\mathbb{R}^{3}$ con $ \vec{y}=\begin{bmatrix}1\\
2\\
3
\end{bmatrix}$ y evaluar su error.

In [3]:
A = np.array([[0.5, 0.0, 0.0,23.0], [0.0, 0.25, 0.0,5.0], [0.0, 3.0, 2.0,3.0]])
y = np.array([[1.0], [2.0], [3.0]])
#calculate the projection
projY_A = projectNonInvertible(y,A)
print("Vector proyectado")
print(projY_A)
print("Error de proyección: ")
error = calculateProjectionError(projY_A, y)
print(error)

Vector proyectado
[[1.]
 [2.]
 [3.]]
Error de proyección: 
1.8576536168699412e-13


### Ejemeplo 4: Menos vectores base $m$ que la dimensionalidad del vector $n$
Dados los siguientes vectores:

$$ \vec{a}_{1}=\begin{bmatrix}5\\
7\\
21
\end{bmatrix},  \vec{a}_{2}=\begin{bmatrix}0\\
13\\
9
\end{bmatrix}$$

Calcular el vector de proyección  $\textrm{proy}\left(\vec{y};A\right)\in\mathbb{R}^{3}$ con $ \vec{y}=\begin{bmatrix}1\\
2\\
3
\end{bmatrix}$ y evaluar su error.

In [4]:
A = np.array([[5.0, 0.0], [7.0, 13.0], [21.0, 9.0]])
y = np.array([[1.0], [2.0], [3.0]])
#calculate the projection
projY_A = projectNonInvertible(y,A)
print("Vector proyectado")
print(projY_A)
print("Error de proyección: ")
error = calculateProjectionError(projY_A, y)
print(error)

Vector proyectado
[[0.56206554]
 [1.9061569 ]
 [3.13555114]]
Error de proyección: 
0.4679393437126663
